### PR TITLE
Use teeny-request

### PR DESCRIPTION
**Pull request by JustinBeckwith**
@fhinkel the system tests currently fail with this error:

```
dns
    1) "before all" hook
(node:39906) UnhandledPromiseRejectionWarning: TypeError: config.request.defaults is not a function
    at Util.makeRequest (/Users/beckwith/Code/nodejs-dns/node_modules/@google-cloud/common/src/util.ts:624:45)
    at onAuthenticated (/Users/beckwith/Code/nodejs-dns/node_modules/@google-cloud/common/src/util.ts:565:24)
    at /Users/beckwith/Code/nodejs-dns/node_modules/@google-cloud/common/src/util.ts:577:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:39906) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39906) UnhandledPromiseRejectionWarning: TypeError: config.request.defaults is not a function
    at Util.makeRequest (/Users/beckwith/Code/nodejs-dns/node_modules/@google-cloud/common/src/util.ts:624:45)
    at onAuthenticated (/Users/beckwith/Code/nodejs-dns/node_modules/@google-cloud/common/src/util.ts:565:24)
    at /Users/beckwith/Code/nodejs-dns/node_modules/@google-cloud/common/src/util.ts:577:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:39906) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
^CTerminated: 15
```

Is this a bug in nodejs-common?  Or am I doing something wrong here?

### CODE REVIEW

**Comment by fhinkel** [comment]
Good morning! It's a bug in `common` that I'm about to fix. See https://github.com/googleapis/nodejs-translate/issues/108#issuecomment-417426234

**Comment by fhinkel** [comment]
How do you know they're failing? Locally? The CI looks green. Or is that because it's a fork?

**Comment by JustinBeckwith** [comment]
They are failing locally.

**Comment by fhinkel** [comment]
Closed via https://github.com/googleapis/nodejs-dns/commit/5c074b709e5cd16bd900c98fab48337850891a17

**Comment by fhinkel** [comment]
Oh, I see. It needs to be 
`const teenyRequest = require('teeny-request').teenyRequest;`

Let me figure out if I want to change to in `teeny` to be more like `request` or at least update the docs for `teeny`.

**Pull request closed without merging**
